// Holds a Regex for each element identifiable. It also sets priorities (what's above is the priority)
const simplePascalSymbols =
{
    BLOCK_BEGIN : /begin/,
    BLOCK_END : /end/,
    DECLARATION_CONST : /const/,
    DECLARATION_TYPE : /type/,
    TYPE : /integer|real|char|boolean/,
    TYPE_ARRAY: /array/,
    TYPE_RECORD: /record/,
    COMMA : /\,/,
    VARIABLE : /var/,
    SEMICOLON : /\;/,
    FUNCTION: /function/,
    PROCEDURE: /procedure/,
    WHILE: /while/,
    DO: /do/,
    IF: /if/,
    IF_THEN: /then/,
    ELSE: /else/,
    FOR: /for/,
    TO: /to/,
    WRITE: /write/,
    READ: /read/,
    ASSIGNMENT: /:=/,
    COLON: /:/,
    EQUAL_SIGN: /=/,
    LOGIC_OPERATOR: /and|or/,
    COMP_OPERATOR: />|<|==|!=|>=|<=/,
    MAT_OPERATOR: /\*|\/|\+|\-/,
    DOT: /\./,
    OPEN_P: /\(/,
    CLOSE_P: /\)/,
    OPEN_B: /\[/,
    CLOSE_B: /\]/,
    STRING: /\"[a-z0-9]*\"/,
    BOOLEAN: /true|false/,
    NUMBER : /\d+|(\d+.\d*)/,
    IDENTIFIER: /(^[a-zA-Z]([a-zA-Z0-9])*$)/,
    ERROR: /\S+/
}

export default simplePascalSymbols;